Fixed missing precompiled stylesheet engine asset
Resolves the following error -- as noted in this link:https://github.com/bkuhlmann/auther/issues/3[issue] -- when launching the app and attempting to login via this engine's UI:

....
Asset `auther/application.css` was not declared to be precompiled in production.
....

This also prevents having to manually declare this asset in your `app/assets/config/manifest.js`.

The Rails _test_ environment check was put in place because, during testing, you'd get the following:

....
FrozenError: can't modify frozen Array: []
....

There doesn't seem to be a better way to handle this at the moment. Even the link:https://guides.rubyonrails.org/engines.html#testing-an-engine[Rails Guides] fails to provide additional details.